services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Tests\Behat\:
    resource: '../tests/Behat/*'

  App\Infrastructure\InMemory\InMemoryFleetRepository: ~

  App\Infrastructure\Persistence\Doctrine\DoctrineFleetRepository:
    arguments:
      - '@doctrine'
