services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Tests\Behat\:
    resource: '../tests/Behat/*'

  App\Domain\Repository\FleetRepositoryInterface: '@App\Infrastructure\InMemory\InMemoryFleetRepository'
